version: "3.7"
services:
  postgres:
    image: postgres:15.4-alpine
    restart: always
    env_file:
      - .env
    #    environment:
    #      POSTGRES_DB: ${POSTGRES_DB}
    #      POSTGRES_USER: ${POSTGRES_USER}
    #      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
